name: cider
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numba>=0.55
  - numpy=2.0.2
  - scipy
  - matplotlib
  - multimethod
  - notebook
  - sunpy>=5.1
  - astropy
  - pyevtk
  - gfortran
  - pip
  - pip:
    - git+https://github.com/pricedj/fishpack
    - git+https://github.com/jpomoell/pysmsh
