name: cider
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - numba>=0.55
  - numpy  
  - scipy
  - matplotlib
  - multimethod
  - notebook
  - sunpy>=5.1
  - astropy
  - pyevtk
  